### ISSUE TITLE
How to write configuration file

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#11]
Which format is the most popular in cloud/container field? Which library is the most popular?

**Comment by s1061123** [comment]
For now, we could use hard-coding / flag (of golang) but in future, we should discuss upstream projects (barometer and SA)

**Comment by yu-kasuya** [comment]
How about to use TOML format? Library is https://github.com/BurntSushi/toml

**Comment by s1061123** [comment]
@yu-kasuya +1!

**Comment by yu-kasuya** [comment]
I just try to write configuration using TOML like below code. How to debug or check code? Using go run xxx.go and Println doesn't work. Is there something good tool?

```
package main

import (
        "fmt"
        "context"
        libvirt "github.com/libvirt/libvirt-go"
        "sync"
        "log"
        "github.com/distributed-monitoring/agent/pkg/annotate"
        "github.com/go-redis/redis"
        "github.com/BurntSushi/toml"
)
type Config struct {
        Redis RedisConfig
}

type RedisConfig struct {
        Ipaddress string
        Port int
        Password string
        DB int
}

var InfoPool annotate.RedisPool

func main() {
        var config Config
        _, err := toml.DecodeFile("../../config/config.toml", &config)
        if err !=nil {
                fmt.Println(err)
        }
        fmt.Println("address", config.Redis.Ipaddress)

        var waitgroup sync.WaitGroup
        libvirt.EventRegisterDefaultImpl()

        redisClient := redis.NewClient(&redis.Options{
                Addr:     config.Redis.Ipaddress,
                Password: config.Redis.Password,
                DB:       config.Redis.DB,
        })

```
```

[redis]
ipaddress = "localhost:6379"
password = ""
DB = 0

```

**Comment by s1061123** [comment]
It works well in my side. here is output:

main.go

```
package main

import (
        "fmt"
        "github.com/BurntSushi/toml"
)

type Config struct {
        Redis RedisConfig
}

type RedisConfig struct {
        Ipaddress string
        Port int
        Password string
        DB int
}

func main() {
        var config Config
        _, err := toml.DecodeFile("config.toml", &config)
        if err !=nil {
                fmt.Println(err)
        }
        fmt.Println("address", config.Redis.Ipaddress)
}
```

config.toml

```
[redis]
ipaddress = "localhost:6379"
password = ""
DB = 0
```

Sample build/output:

```
[tohayash@tohayash-srv toml1]$ go run main.go 
address localhost:6379
[tohayash@tohayash-srv toml1]$ go build main.go 
[tohayash@tohayash-srv toml1]$ ./main 
address localhost:6379
```

**Comment by takahashi-tsc** [comment]
Thank you for library selection and check.
It also works in my environment.

Where should the config files be placed?

- Dir: /etc/barometer-localagent/
- Files:
  - server.toml
  - infofetch.toml
  - threshold.toml

**Comment by yu-kasuya** [comment]
Thanks, I have another question to write go, I want to ask next MTG.
Is that good to separate config files with each function? I have no idea.

**Comment by takahashi-tsc** [comment]
I think that if different people edit the file, we should separate it.

- config for "server": infrastructure constructor
- config for "infofetch" and "threshold": DMA user/developer

But Redis URI may be set by the infrastructure constructor... We need discussion.

**Comment by takahashi-tsc** [comment]
I try adding threshold config. I'd like to discuss about file separate based on the change.

 #31

**Comment by s1061123** [comment]
In the meeting:
 + create one file for all local-agent process
 + separate section for each process and put common section for all processes.

**Comment by takahashi-tsc** [comment]
Other details...

- The config file path/name will be "/etc/barometer-localagent/config.toml"
- Create new PR by merging #28, #31, #33.
- Refer to barometer-collectd etc for where to put config in our repository.
