### ISSUE TITLE
Determine the name prefix

### ISSUE THREAD

**Issue by takahashi-tsc** [distributed-monitoring/agent#21]
Now, names of created binaries are "server" and "threshold".
Because these are too general names, we need to prefix.

- barometer-localagent-
- barometer-local
- barometer-agent
- (etc...)

 I think that it is unnecessary for pkg.

**Comment by yu-kasuya** [comment]
+1
In barometer repository, they use barometer-xxx for docker. I think localagent is good, because agent is not only local side, the central server has also a management agent.

**Comment by takahashi-tsc** [comment]
Should we resolve this issue before Gambia release?

**Comment by yu-kasuya** [comment]
In my understand, prefix name for binaries is not necessary. To use prefix name for docker is needed in Barometer repository. So we have to re-think the structure of container, to separate each binary to one container or all binaries are in one container. IMO, later is good at this time.

**Comment by takahashi-tsc** [comment]
Thank you for the comment. Your comment looks right, so now Gambia milestone tag is not needed.
But I think we should care about how local-agent is installed and used. I want to reconfirm this issue when considering installer and dockerize. (Let's discuss at the meeting)

**Comment by yu-kasuya** [comment]
We use "barometer-dma"
