### ISSUE TITLE
Write tests of Functest

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#24]
- To create new test python code under baro_tests
- check data in redis
- check collectd config file
- check collectd and redis process status
- etc...

**Comment by s1061123** [comment]
FYI:
https://gerrit.opnfv.org/gerrit/#/c/39529/

**Comment by yu-kasuya** [comment]
It works well in my environment.
https://github.com/distributed-monitoring/barometer/pull/1

**Comment by yu-kasuya** [comment]
Merged in Barometer repo.
