### ISSUE TITLE
Dockerize of DMA functions

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#25]
To use centos:7 or alpine?

**Comment by s1061123** [comment]
We may need to consider should we add golang itself to containers...

following url could be help:

- http://naoty.hatenablog.com/entry/2017/09/18/121840
- https://shotat.hateblo.jp/entry/2017/08/05/215211

**Comment by yu-kasuya** [comment]
Done #55. Thanks
