### ISSUE TITLE
Ask Barometer to install collectd-write_redis

### ISSUE THREAD

**Issue by takahashi-tsc** [distributed-monitoring/agent#27]
Our code needs collectd-write_redis. Barometer uses a quite new version of collectd, so we can not install collectd-write_redis later.

**Comment by s1061123** [comment]
Your fix, https://github.com/collectd/collectd/commit/a3bafd5a952b5cfacacb03f9fb2ac5988d1e39fb will be merged at next collectd release. So that is a concern.

**Comment by s1061123** [comment]
Submit https://gerrit.opnfv.org/gerrit/59635

**Comment by yu-kasuya** [comment]
Merged. Thanks
