### ISSUE TITLE
Exported name control in pkg

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#37]

**Comment by s1061123** [comment]
Will check it by 7/23.

**Comment by s1061123** [comment]
I've checked it under cmd/* and pkg/*. All func name in cmd/* is okey because they are main package.
(for infofetch/*, openstack and libvirt function has functions begins with capital but it is explicitly named for API-ish call)

The functions under pkg/* is also checked and they are okey.

**Comment by yu-kasuya** [comment]
Thank you for checking.
