### ISSUE TITLE
Developing a function that getting some Info

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#7]

**Comment by yu-kasuya** [comment]
There are two go libraries to use OpenStack API. We have to consider which is better for us.
- https://github.com/openstack/golang-client
- https://github.com/gophercloud/gophercloud

**Comment by s1061123** [comment]
Need to clarify use-case with following information:

- which information is required (hostname)?
- where we get information (openstack or libvirt)?

**Comment by yu-kasuya** [comment]
Creating annotation function

**Comment by yu-kasuya** [comment]
Can I close this issue, due to #23 .

**Comment by takahashi-tsc** [comment]
I agree. I think we can close this issue.

**Comment by yu-kasuya** [comment]
Thanks!
