### ISSUE TITLE
Writing documantation

### ISSUE THREAD

**Issue by yu-kasuya** [distributed-monitoring/agent#9]

**Comment by s1061123** [comment]
- [ ] README.md
- [ ] Architecture document (including UML?)

**Comment by takahashi-tsc** [comment]
README.md is following?
- How to configure LocalAgent (and/or how to validate the feature)
- How to use LocalAgent
- How to achieve distributed monitoring and analysis (=collectd, evaluator and transmitter setting)

**Comment by takahashi-tsc** [comment]
I'll write...
- [ ] Getting started
- [ ] Distributed Monitoring Guide

I should write how to use what I made.

**Comment by yu-kasuya** [comment]
User guide for Docker https://github.com/distributed-monitoring/barometer/blob/docs/localagent/docs/release/userguide/docker.userguide.rst#build-and-run-localagent-and-redis-docker-images

**Comment by yu-kasuya** [comment]
Merged in Barometer repo. If you need to fix, you can do it in Barometer repo.
